#!/usr/bin/env python3
# -*- coding: UTF-8 -*-


class Config:
    MAP_SIZE = 128
    LOCAL_MAP_SIZE = 21
    LOCAL_HALF = 10

    ACTION_DIM = 16
    ACTION_NUM = 16
    ACTION_SHAPE = (ACTION_DIM,)
    VALUE_SHAPE = (1,)
    VALUE_NUM = 1

    MAP_CHANNEL = 1
    MAP_OBS_SIZE = 1
    MAP_OBS_SHAPE = (MAP_CHANNEL, MAP_OBS_SIZE, MAP_OBS_SIZE)
    MAP_SIZE_OBS = 1
    VECTOR_FEATURE_LEN = 16
    FEATURE_VECTOR_SHAPE = (VECTOR_FEATURE_LEN,)
    FEATURE_IMAGE_SHAPE = MAP_OBS_SHAPE

    VISIT_DECAY = 0.965
    RAY_MAX_LEN = 18
    ASTAR_MAX_EXPAND = 8000

    USE_CNN = False
    VIEW_SIZE = 0

    GAMMA = 0.95
    LAMDA = 0.95
    START_LR = 5e-4
    VALUE_LOSS_COEFF = 0.5
    ENTROPY_LOSS_COEFF = 0.025
